# Test Url
#baseUrl: http://localhost:4000

# Production Url
baseUrl: https://pocketlika.github.io

# Blog settings
twitterUrl: http://twitter.com/pocketlika
email: pocketlika@gmail.com
paginate: 2

# Build settings
gems:
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
