# Test Url
#baseUrl: http://localhost:4000

# Production Url
baseUrl: https://pocketlika.github.io

# Social Media
linkFacebook: https://www.facebook.com/pocketlika
linkTwitter: http://twitter.com/pocketlika
linkBloglovin: https://www.bloglovin.com/blogs/feliz-assim-14224049
linkYoutube: https://www.youtube.com/channel/UCTk3xkOSzWzf8Ba-wJN8jDA
linkPinterest: https://br.pinterest.com/heylika/
linkInstagram: https://www.instagram.com/heylika/

# Blog Settings
title: hey, Lika
description: Blog
email: pocketlika@gmail.com
paginate: 10
permalink: pretty

# Build Settings
gems:
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
